from collections.abc import Mapping, Sequence

import numpy as np
from numpy.typing import ArrayLike, NDArray

class DataType: ...

class Schema:
    names: list[str]

class ChunkedArray:
    null_count: int
    def to_numpy(self) -> NDArray[np.generic]: ...

class Table:
    column_names: list[str]
    def __getitem__(self, key: str) -> ChunkedArray: ...

def table(
    data: Mapping[str, ArrayLike | Sequence[object]], *, schema: Schema | None = ...
) -> Table: ...
def schema(fields: Sequence[tuple[str, DataType]]) -> Schema: ...
def int16() -> DataType: ...
def int64() -> DataType: ...
def float64() -> DataType: ...
def string() -> DataType: ...
