from os import PathLike

from . import Schema, Table

def read_schema(where: str | PathLike[str]) -> Schema: ...
def read_table(source: str | PathLike[str], *, columns: list[str]) -> Table: ...
def write_table(table: Table, where: str | PathLike[str]) -> None: ...
